apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "example.com/v1alpha1",
          "kind": "MvcDb",
          "metadata": {
            "name": "mvcdb-sample-1"
          },
          "spec": {
            "backend": {
              "image": "quay.io/rhm_samples/nodejs-guestbook-backend:v0.0.1",
              "imagePullSecrets": [],
              "replicaCount": 1,
              "service": {
                "port": 8080,
                "targetPort": "http-server",
                "type": "NodePort"
              }
            },
            "frontend": {
              "image": "quay.io/rhm_samples/nodejs-guestbook-frontend:v0.0.1",
              "imagePullSecrets": [],
              "replicaCount": 1,
              "service": {
                "port": 8080,
                "targetPort": "http-server",
                "type": "NodePort"
              }
            }
          }
        }
      ]    
    capabilities: Basic Install
    categories: Developer Tools
    certified: "false"    
    createdAt: "2020-12-03T12:00:00Z"
    repository: https://github.com/rhm-samples/helm-operator/tree/main/mvc-db-app-operator
    support: IBM Edge
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: mvc-db-app-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Deploy MVC-DB-APP with MongoDB,Guestbook application Frontend and Backend
      displayName: MvcDb
      kind: MvcDb
      name: mvcdbs.example.com
      resources:
      - kind: Route
        name: ''
        version: route.openshift.io/v1
      version: v1alpha1
  description: This operator will deploy a multi-image application consisting of MongoDB,Guestbook Frontend and Guestbook Backend
  displayName: MVC-DB-APP Operator
  icon:
  - base64data: "iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAwFBMVEX///8AAADMAADRAADPAADTAADLAADGAAD6+vrIAADw8PDU1NSdnZ2tra2mAAC4uLhmZmZra2vIyMi7AAAfAACyAADp6elPT0/a2tqVAAAqAACIiIiwAABmAACDAAAoKCgwAAB7AAB0AABWAAA2NjawsLAmAACPAABBAABQAABCQkJgAACGAACcAAARAABXV1caGhp1dXWgoKAYAAAuAAATExOMjIw+AABhAAAlJSU3AABrAAAHAAC+vr5GRkYyMjJWPdlOAAAOc0lEQVR4nO1d6VriMBQV2lB2wbKVRQREqICCDuoMLu//VtMN6JI096YtIB/n34yl7WmSu+fm6ippZPOF61KxU2ne95frlIn1sn/frHSKpetCPpv485NEo1XqVO5T4bivdMatxrFfVQCFUvWRw82Nx2qpcOxXRqBQbCLI7dEs/gaW+XFViN0W1XH+2BTC0Hp5jkTPxvPLiS7LfElsbtLQLJ3eSN5UYqNno3JzbEpu5It/Y+Znol88lYEsrBKgZ2N1CsK1EN/qo6F5bI43PJMlOh6PuSBvvhPnZ+L7WBwTnp9uPB9jrjbiVg/hqB7aCsi+HZSfieJBHa2v/sEJGvrxcMsxf9gJukflQCbA+Ej8TFwfgN+BJYwflcQlzvX6qARTqXXCw5icCQrHKkF+rWOI0CD6raQIXsf8pg/6Zl7umihrw9E/xC8Tmqkd6PNr/3R9+t4Ov2g0UXOESLINSSIZVZuBKXYS4JcFWaGfM00139eEnKlrg+kT5aqn2SJt/D3thWywnDwAKTZjt3AaS8Bj3zWZuF/cHBqiLgb6+8Onw609/dC6xtil6ZAkrQajuIxZbdxAHjqRaC9uDCkhilo3odoz0/MNjL8SaT+iUm4Do5iK1YiDyJiaShgDY/O04J2URClrk+HmozecLNTdwJIFkOJXfARfAI97yPnXVRhkkuveTr13GGmK/Y1IHUjxJS6CIE9JxRCUuptP2k2GOWscpTKQYjEegiAtobFkBw2Z91Rb7202m57+x3ubWte6D5kAKcaiNUCG2hRDMJ1WMmlTwJhLL9MdeO7UteYC6QEpxmDCwSzRMmaOeiGTjO660529FmWg0ohOEWbI3OGG0Aep674X7f/CEHGiAsMxt1EYyt4pudUZ0HkaTdxA1IQJlCD181NG7lsNth9LeYVSjKA0oM7EZ5iuD6cn14eeW/V2s0GCytMIqh9kqlmvJcqwPHz33Ki9cE13+Q5MUdCAa4AfgFKGLniEqGHUGB6H669gvW9AyAzPQrwJG4rgEKYJ6WrzzWw028y1OiG+1Uym/Ec7WIo4U/CsRDuzfSVFDXh9HFgOluVdBH8ogzWG4S/iCYI9+lTqw1mGZPj6+a5GUo1eSDr/4Vug1SImJjORHILWv2KkiBlEbOymhbh1qm5NMFm1//VaF5WsQWAGMYWLwGHChg85+20G2//QHF9Wdjx4e6GJGAUyQpym+hiCqMCv7vite9NkusgYnHL18kK73cx0faqPhoasFJi+BBNjRBjhuMCoY5SSEee6p4GC5ihBIxoWwLYNXNVbcDwnAoggLfAUoV6UiTVU8SOzS46+B62ZOnY1SnPMq1RgBJH5wbut6ITYkRP0ICrUgA4LIJWRxxFMDXcMASEy9BhutSwUkCwxNgO6X1vcQKdexotTyHdzATBPv5AE3Wa3pNKlTXs62wwnXbTRan83uP1tgutIZbEpwlf3sMg+gVqbzRd1S/NTTWsQcAoj1ed5Geg6mQ/fxNtL93dNtdJnYsRcFHEvxAnbIFWhgbmX4c5Yfl0Ij5oPSFnD8YbxhRZ+6ehMqlp8LsbWpIeiGkawgCYY9O9J+cmwxpV4xs+ChJM1qbAyP3ypfS0YwZByCw2ViOIyhEfdLDyzCYKDa3vc5SivJMfo55tQUXZNmMYQKIht0xjGDa7b4gMzaCMwhBHibAjIOJXIHkShmu1unCuOhRytoiMEj3SCAoI05TK8kwSBV9rYoItTwbLtQyxEVLzGBHUlig3hPlqaKJCWGz3wxo0+tfVZbzi4nd/eDgab3ky/c9Jf2gEooqcpJSoV6vjqg4Way8h2bY/kVPnsTNBy8hQlDcmQ4goXWZc+DMv0tMLeUzrAKCpYhkEXg7H7bFSW/CmhLTL7JO0wHbMVEwAq+m0iEB+ma3u9zqLnCy/867IvjIfhLZJhQOtT3SYt7LV99vBMTZQjMlyTCkRsaHKmHVqKF/yqPbE4DBA5TkVuEN5wRil4Ac/Fo8ybUTmd2EAS7EJMjT0MKfYMr4KEKsDbA1Usy8QFLvhtwmPXUNKFE54GYAUX/tyqSYwk2nDzBmyClUF3gIcyV8bdphz7UGKjNQZKLobB6MUtX4mHCvCn6aCsCOZFGRTRDF3RDIokhbh9Csdr+7zbWCHTeGgSpI+YcltuwWzTK8R1h0WIpkNNzcUwmASTSbSxl6bBZh21DP+RiPhJbTSvRxU/Agz3kVPKK8HCL5k/wZ+y8GdTFsnk7xlas/QVFZTaEqT5vrB6SllBWRqv85w4R9u70Ilcn4MjxNtgBs1xApY1ywqmWMLAQJSjow81ydyooWg6KIS6rTylBWg2QJdPziBjmQ+C/rLjjTqrRyLqHPBtm8xlaCxEcIAJ7deI+cuKJWj2H16W0mW+qcpehpiaUdJFmv0ihf2OZvIIQJnUeRwLLL/CQBu+XuQ0LsNXE1iKGesr+i0tmZTD5+qYoQ0tYApD+B/TA/wg2kOoB38npUMXia0RWX3VMClAWeoihCq+LtwySukeK1FD6ni+TYLMxPYINZmMCQNWUw9Yhlai+w/jk8tSSDC1QfcNHXBdxABH6FxF7s+wPKcRO+tKBswntZiCxkIdKRJkqQ7b6YIs/pJGnJ8Q5mI0RU1YQTc6Gy8TZQDY64Lc6pae9jimELNewyz/Diu/+CeQjyfygj9ZkfVthLteWG6OKUxD86I6mmDaMqkGnF3nUKMQDoXuXN1fXWXDX0UXehWZZMrh2aI4q1EssIrDstxiy6lg2ZZM5DAHQOzLhYERUM3zE6NT4doYY7aySSJVER+McGMBULX+HmFGGa7cgjFdF3FTpIc5vsLU4RavkWrUJMPNGdIeHmnjKe1BA9rLl9iZUTciZnllYszXUcDHGsZLkb6H6AW4g2sedUrJEknXtZ5nQ2Xcg5ihvXkHWm85iyGsa7JU6pPhyIzQPfQi7HBngOZkVMFVNO2YCkad5jUSM3ke4dY0fdFElHodoqokEiSa5XaP2aX2kUm6HiEaqAz7V/Ddvsba6Z70MMo0F3x5heswt0m8rCQCMjS/bU0Nlobg7gAFUKKgVxVhGZ7wMDLqbPEMU0/lhKuDBMHw8wUYGq5PeKXNkcBIMAoxTKUGp6c4WFVTSFm6w8Pi1KYqI6S4RulDD97rSRZ54ZGjx/iWqJ33Pnyc0nJklU30xbYgbDFUToYjq6TgXrRC38Hn4ES0I2GVvTUF9uP5EKX6IDbIzCrpKqZLCwO1+fHnKrs2swOL0wTw03l76+wSj6+3ueNyDOlCWITE2gLYNtXO7msaDZlzPN0R1lGqJNL+2FV8m93vQ9kcTT/KYfsTvwQ2A3k7M7i+kF6mNqFNnGBo77oCuklEoCGTex/DPy2BABMHkhKa58rzck8BrAPbbbxdGIbqYQdSqofXnWavrn5wDCk9tXxdCvRF5nADSTjl3/ecHDAFtA2ofrvIqtg/BD+ZW3JW5eTxKaB1LKCs5amW3NaLHSSFW+DSCa/FoGBJIci4R6+c7GyVZUAV9ji0noaGNb11CL2uqj3sJiZbZdKFVCiZ9TTIZh/0vho7leF3xu4G9SQ20chEhdW1NtjfnwXGVnfbtlllKeu6Nohcxe7nJ6nAXbNWXRurNpEBVgdGg9iy5CLrJbkpK3ENpVnnAa5LrrLFBBNLVq+pfMv5S5Ya3HrSJ3UpOkuJqLfw3rSOCY20TN8YDPdg3rA2s9sOiY6eRJQJrpOLXSOMtdv4TXtDO77N5l0lje2uZLaaynUHiNGz4bwQtqUJv3cfb2//9GPeVTOwLlLm+RiSWh6M8PuedrX6WDe/z2/7BjEF/0x7k0VXIc4JHl6yu86gSncx0P8hG9Rssd1vgXYR7/l9ieHz4rM97d3OtUW3ru52QOTUenkxmQ9HotQc7BqAcK57/P5+9IbGAU17D3f8Ywh2bxOmEe9L1rLL33gu4i/FbBzHO0fEfu8aW/b1XSGLgkvPhTSb2uH4FPcBJVYko+JtZJN1OcuQdq9HP6TNJREpn/tv5TogMt1GOqTd6zFPSkx5J5pvL/f36qVF1Qiu65aQ5tKt5I8LDoF7L3e+5GD8ddPIhugCtx+yggxjDCeyrkRnu9BxAl5nkm+iGr9gCerlfaU4vi6tXIv7eVwofBU93px5xDo64GlDoNW+CW/osMT/gTFV3/zhvOXzalzYLYOCbQCt37bfvFFy5EJlnA8+EwzQy1HgkR6hbSb3yLaKncpzs/lcXXXeSoWGf403ip3Ol+c/862v8U4UCM504dP1Wi7zBjJNo0Os1ADY+ZqK4nbWPR/kmGV811gL0Y7Wa113Vp1SYseBegE9sMgL1DkCRwYuUrZFTIfOHQK4eO4OBzrgOg6IpeGTPDQ4bog5mgeSEXFATJIK2jNHgVhLzrB20KcGoYOkGT1oTxNC2jDWg3SFkW94LKLxmH6ZiCg9iVX4Yhqbz/tYyI0rMOaBiNl9CkO4TcE9OlLddJDoAl6g7g4SJksaLhVgRQqsqUhnKFA7eQqC1GOJ/XV0Ov1SPEGg05osaHEJ+mmiAhGM07BIDS13743DfdMvxJdOnpJTkXXJyR/Gl0e7Tj8H8crBaG3Nala0gGOzrf/2f35+/rrT6qegKTy4Wf2k/laYOQJW7qNZ7VwXWq1GPmui0WoVrjtVc7yjRGeSQjYkAk3tUM0KyJsRuuJpiBkwgodPLd9OQdnFB7/F9nxyiywi/BGan2O/UOzwz1GGyvy9CNjczHKsX4qgHBU6mvp0QYlAiSaTThQBRdE/M0Hqcwsfz0wP+jRhcyyUrz5p3Jzx7LThIniYJOyh4dKEZzmALkUBPob6l2F17gT3fv2ZWWk77KpvznQE96rw3HT8Frs5emZW6A75bdzsPPXg1T649psqDVDonPsIOint719USYGDJWXWq3MVogaa60rn5lzV/AUXXHDBBRdccMEFF1xwwQUXXHDBBRdccMEFF0TFf1UCVwM7IDX5AAAAAElFTkSuQmCC"
    mediatype: "image/png"
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - example.com
          resources:
          - mvcdbs
          - mvcdbs/status
          - mvcdbs/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          - persistentvolumes
          - nodes
          - events
          - secrets
          - secrets/finalizers
          - pods
          - pods/finalizers
          - serviceaccounts
          - services
          - configmaps
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - '*'
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - anyuid
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          - secrets/finalizers
          - pods
          - pods/finalizers
          - pods/exec
          - pods/log
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - persistentvolumes
          - persistentvolumeclaims/finalizers
          - persistentvolumes/finalizers
          - nodes
          - events
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: mvc-db-app-operator
      deployments:
      - name: mvc-db-app-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: mvc-db-app-operator
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: mvc-db-app-operator
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.6.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                - --leader-election-id=mvc-db-app-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: mvc-db-app-operator
                - name: RELATED_IMAGE_BACKEND
                  value: quay.io/rhm_samples/nodejs-guestbook-backend:v0.0.1
                - name: RELATED_IMAGE_FRONTEND
                  value: quay.io/rhm_samples/nodejs-guestbook-frontend:v0
                image: quay.io/rhm_samples/mvc-db-app-operator:v0.0.1
                imagePullPolicy: Always
                name: manager
                resources: {}
              serviceAccountName: mvc-db-app-operator
              terminationGracePeriodSeconds: 10
        serviceAccountName: mvc-db-app-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - mongo
  - mvc-db-app-operator
  - frontend
  - backend
  links:
  - name: Mvc Db App Operator
    url: https://mvc-db-app-operator.domain
  maintainers:
  - email: edge@us.ibm.com
    name: IBM-Edge
  maturity: alpha
  provider:
    name: IBM Edge
  version: 0.0.1
